project-id="mostafa-ahmed-gomaa"
region="us-central1"
zone="us-central1-a"
vpc-name="task-vpc"
subnet1-name="management-subnet"
subnet2-name="restricted-subnet"
subnet1-cidr="10.0.9.0/24"
subnet2-cidr="10.0.10.0/24"
