apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypython-app
  labels:
    name: my-app
spec:
  template:
    metadata:
      labels:
        name: my-app

    spec:
      containers:
        - name: app-container
          image: gcr.io/mostafa-ahmed-gomaa/my-python-app:v1.0
          ports:
          - containerPort: 8000 
          envFrom:
          - configMapRef:
              name: my-app-cm

  replicas: 3
  selector:
    matchLabels:
      name: my-app
  

